### ISSUE TITLE
Cannot Reproduce PCPL Results

### ISSUE THREAD

**Issue by zhanwenchen** [coldmanck/recovering-unbiased-scene-graphs#2]
Hi,

I have not been able to reproduce the 35.2 mR@50 result of PCPL. The best validation accuracy for PredCls mR@50 I got was 24.92. From what I understand, nor can anybody else so far. For example, [the SHA+GCL paper](https://arxiv.org/pdf/2203.09811.pdf) reports 22-24 in their supplemental materials (page 12). The command I used was based on your README.md:

```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port 10025 --nproc_per_node=2 tools/relation_train_net.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX True MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 48 TEST.IMS_PER_BATCH 2 DTYPE "float16" SOLVER.MAX_ITER 50000 SOLVER.VAL_PERIOD 2000 SOLVER.CHECKPOINT_PERIOD 2000 GLOVE_DIR glove MODEL.PRETRAINED_DETECTOR_CKPT checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR output/motif-precls-exmp-pcpl LOG_TB True SOLVER.PRE_VAL True MODEL.PCPL_CENTER_LOSS True
```

My specific code is at https://github.com/zhanwenchen/recovering-unbiased-scene-graphs/blob/main/scripts/train_slurm.sh.
[log_train.log](https://github.com/coldmanck/recovering-unbiased-scene-graphs/files/10714730/log_train.log)

My log is attached.

**Comment by coldmanck** [comment]
Hi @zhanwenchen Thank you for your interest in our work! Please note that the performance reported in the original PCPL paper (i.e. 35.2 constrained mR@50 under PredCls) include both i) the PCPL learning strategy and ii) their graph encoding module (backbone) composed of Transformer layers, and the authors didn't provide ablation results on each of them. We implemented only the PCPL learning algorithm and report its performance based on either MOTIFS or VCTree backbone.

**Comment by zhanwenchen** [comment]
@coldmanck is the transformer the same as the Kaihua Tang transformer (TransformerPredictor)? Thank you so much for your response. I also emailed the PCPL authors too.

**Comment by coldmanck** [comment]
I think you'd need to check with the PCPL authors for that - I am not pretty sure about that.
